# Generated by Django 5.2.8 on 2025-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagecreator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercreatedimage",
            name="overlay_img",
        ),
        migrations.AddField(
            model_name="usercreatedimage",
            name="border_color",
            field=models.CharField(default="#ffffff", max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usercreatedimage",
            name="final_image",
            field=models.ImageField(blank=True, null=True, upload_to="final_images/"),
        ),
        migrations.DeleteModel(
            name="Overlay",
        ),
    ]
