# Generated by Django 5.2.8 on 2025-11-18 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imagecreator", "0002_remove_usercreatedimage_overlay_img_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercreatedimage",
            name="background_color",
        ),
    ]
